name: Generate Raspberry Pi OS Image

on:
  push:
    branches:
      - ci
  workflow_dispatch:

env:
  ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}

jobs:
  build-pi-image:
    runs-on: ubuntu-latest
    steps:
      - name: Create stargate software installer stage
        run: |
          mkdir -p stage-custom/package-custom
          echo "#!/bin/bash" > stage-custom/package-custom/00-run.sh
          echo "set -e" >> stage-custom/package-custom/00-run.sh
          echo "export ROLLBAR_TOKEN=${{ env.ROLLBAR_TOKEN }}" >> stage-custom/package-custom/00-run.sh
          echo "apt-get install git -y" >> stage-custom/package-custom/00-run.sh
          echo "cd /home/pi" >> stage-custom/package-custom/00-run.sh
          echo "git clone https://github.com/jonnerd154/StargateProject-software.git sg1_v4" >> stage-custom/package-custom/00-run.sh
          echo "chmod u+x /home/pi/sg1_v4/install/*.sh" >> stage-custom/package-custom/00-run.sh
          # echo "cd /home/pi/sg1_v4/ && wget ${{ secrets.SOUNDFX_URL }}" >> stage-custom/package-custom/00-run.sh"
          # echo "mkdir -p soundfx && unzip soundfx.zip -d soundfx && mv soundfx/soundfx soundfx/milkyway" >> stage-custom/package-custom/00-run.sh
          # echo "cd /home/pi/sg1_v4/install && ./install.sh" >> stage-custom/package-custom/00-run.sh
          # chmod +x stage-custom/package-custom/00-run.sh
          cat stage-custom/package-custom/00-run.sh

      # - name: Run pi-gen-action
      #   uses: usimd/pi-gen-action@v1
      #   id: build
      #   with:
      #     hostname: stargate
      #     username: pi
      #     password: sg1
      #     image-name: sg1_v4
      #     keyboard-keymap: us
      #     locale: en_GB.UTF-8
      #     enable-ssh: 1
      #     export-last-stage-only: true
      #     #compression: zip
      #     compression: none
      #     #compression-level: 6
      #     stage-list: stage0 stage1 stage2 ./stage-custom

      # - name: Upload image artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sg1-v4-image
      #     path: ${{ steps.build.outputs.image-path }}